/* Generated By:JavaCC: Do not edit this line. PDFParserConstants.java */
package com.reportmill.pdf.reader;

public interface PDFParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int WHITE = 6;
  int TO_EOL = 7;
  int BOOLEAN_TRUE = 8;
  int BOOLEAN_FALSE = 9;
  int NULL_OBJECT = 10;
  int NUM_INTEGER = 11;
  int NUM_REAL = 12;
  int PDF_HEX_STRING = 13;
  int PDF_NAME = 14;
  int ARRAY_BEGIN = 15;
  int ARRAY_END = 16;
  int DICT_BEGIN = 17;
  int DICT_END = 18;
  int STREAM_END = 19;
  int STREAM_BEGIN = 20;
  int TRAILER = 21;
  int XREF = 22;
  int START_XREF = 23;
  int XREF_F = 24;
  int XREF_N = 25;
  int OBJECT_BEGIN = 26;
  int OBJECT_END = 27;
  int PDF_COMMENT = 28;
  int PDF_STRING = 35;
  int PDF_HEADER = 40;
  int EOF_MARKER = 41;

  int DEFAULT = 0;
  int IN_STRING = 1;
  int IN_STRING_NEST = 2;
  int SPECIAL_COMMENTS = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DIGIT>",
    "<WHITE>",
    "<TO_EOL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<NUM_INTEGER>",
    "<NUM_REAL>",
    "<PDF_HEX_STRING>",
    "<PDF_NAME>",
    "\"[\"",
    "\"]\"",
    "\"<<\"",
    "\">>\"",
    "\"endstream\"",
    "<STREAM_BEGIN>",
    "\"trailer\"",
    "\"xref\"",
    "\"startxref\"",
    "\"f\"",
    "\"n\"",
    "\"obj\"",
    "\"endobj\"",
    "<PDF_COMMENT>",
    "\"(\"",
    "\"(\"",
    "\"\\\\(\"",
    "\"\\\\)\"",
    "\")\"",
    "<token of kind 34>",
    "\")\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PDF_HEADER>",
    "\"%%EOF\"",
    "\"R\"",
  };

}
